# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-25 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add_problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hostname', models.CharField(max_length=125)),
                ('IPaddress', models.GenericIPAddressField()),
                ('ProblemUser', models.CharField(max_length=30)),
                ('ProblemTime', models.DateTimeField(verbose_name='\u62a5\u4fee\u65f6\u95f4')),
                ('Issue', models.TextField(verbose_name='\u95ee\u9898')),
                ('Resolve', models.TextField(blank=True, null=True, verbose_name='\u89e3\u51b3\u65b9\u6cd5')),
                ('ProblemStatus', models.CharField(choices=[('yes', '\u4ee5\u89e3\u51b3'), ('no', '\u672a\u89e3\u51b3')], default='no', max_length=10, verbose_name='\u662f\u5426\u5b8c\u6210')),
                ('ResolveUser', models.CharField(max_length=20, verbose_name='\u5904\u7406\u4eba')),
            ],
        ),
    ]
